version: "3.7"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=backend
    logging:
      driver: none

#  server:
#    build: .
#    ports:
#      - "8000:8000"
#    environment:
#      - DB_HOST=postgres
#      - DB_PORT=5432
